variable "aws_region" {}
variable "aws_profile" {}
variable "key_name" {}
variable "instance_type" {}
variable "ami_id" {}
variable "subnet_id" {}
variable "vpc_id" {}
variable "cluster_sg" {}
variable "capa_user" {}
variable "capa_policy" {}
variable "domain_name" {}
variable "hosted_zone_id" {}